[16-Jun-2022 14:01:19 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\MVC\public\index.php(35): Core\Router->dispatch('favicon.ico')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\MVC\Core\Router.php' on line 130
[16-Jun-2022 19:22:47 Europe/Berlin] Uncaught exception: 'Exception' with message 'Method action (in controller App\Controllers\Posts) not found'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('posts/action')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 124
[16-Jun-2022 19:23:01 Europe/Berlin] Uncaught exception: 'Exception' with message 'Method idAction not found in controllerApp\Controllers\Posts'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('id', Array)
#1 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('posts/id')
#2 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php' on line 49
[16-Jun-2022 19:55:29 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('favicon.ico')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 20:13:04 Europe/Berlin] Uncaught exception: 'Exception' with message 'Controller class App\Controllers\Admin not found'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('admin/index')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 127
[16-Jun-2022 20:13:07 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('admin/index.htm...')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 20:18:34 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('Home.php')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 20:18:39 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('Home.php')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 20:28:31 Europe/Berlin] Uncaught exception: 'Exception' with message 'Controller class App\Controllers\Signup not found'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('signup/new')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 127
[16-Jun-2022 20:31:24 Europe/Berlin] Uncaught exception: 'Exception' with message 'Controller class App\Controllers\Signup not found'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('signup/new')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 127
[16-Jun-2022 20:36:07 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('User')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 20:39:24 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'Undefined array key "userlogin"'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php(50): Core\Error::errorHandler(2, 'Undefined array...', 'D:\\Dropbox\\#pro...', 50)
#1 [internal function]: App\Controllers\Home->loginAction()
#2 D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php(45): call_user_func_array(Array, Array)
#3 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('login', Array)
#4 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('Home/login')
#5 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php' on line 50
[16-Jun-2022 20:56:47 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('Login')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 20:58:04 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('create')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 20:59:37 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('create')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 21:01:13 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('create')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 21:01:21 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('create')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 21:04:54 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mvc.users' doesn't exist'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\App\Models\User.php(53): PDOStatement->execute()
#1 D:\Dropbox\#programování\#projekt\ins_app\App\Models\User.php(68): App\Models\User::findByEmail('bobiufi@gmail.c...')
#2 D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Login.php(19): App\Models\User::authenticate('bobiufi@gmail.c...', 'ngg')
#3 [internal function]: App\Controllers\Login->createAction()
#4 D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php(45): call_user_func_array(Array, Array)
#5 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('create', Array)
#6 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('Login/create')
#7 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\App\Models\User.php' on line 53
[16-Jun-2022 21:05:10 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'Undefined array key "userlogin"'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php(50): Core\Error::errorHandler(2, 'Undefined array...', 'D:\\Dropbox\\#pro...', 50)
#1 [internal function]: App\Controllers\Home->loginAction()
#2 D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php(45): call_user_func_array(Array, Array)
#3 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('login', Array)
#4 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('Home/login')
#5 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php' on line 50
[16-Jun-2022 21:05:37 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'Undefined array key "userlogin"'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php(50): Core\Error::errorHandler(2, 'Undefined array...', 'D:\\Dropbox\\#pro...', 50)
#1 [internal function]: App\Controllers\Home->loginAction()
#2 D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php(45): call_user_func_array(Array, Array)
#3 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('login', Array)
#4 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('home/login')
#5 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php' on line 50
[16-Jun-2022 21:06:02 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'Undefined array key "userlogin"'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php(50): Core\Error::errorHandler(2, 'Undefined array...', 'D:\\Dropbox\\#pro...', 50)
#1 [internal function]: App\Controllers\Home->loginAction()
#2 D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php(45): call_user_func_array(Array, Array)
#3 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('login', Array)
#4 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('home/login')
#5 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php' on line 50
[16-Jun-2022 21:07:58 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'Undefined array key "userlogin"'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php(50): Core\Error::errorHandler(2, 'Undefined array...', 'D:\\Dropbox\\#pro...', 50)
#1 [internal function]: App\Controllers\Home->loginAction()
#2 D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php(45): call_user_func_array(Array, Array)
#3 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('login', Array)
#4 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('home/login')
#5 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php' on line 50
[16-Jun-2022 21:08:03 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'Undefined array key "userlogin"'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php(50): Core\Error::errorHandler(2, 'Undefined array...', 'D:\\Dropbox\\#pro...', 50)
#1 [internal function]: App\Controllers\Home->loginAction()
#2 D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php(45): call_user_func_array(Array, Array)
#3 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('login', Array)
#4 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('home/login')
#5 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php' on line 50
[16-Jun-2022 21:25:38 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('create')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 21:25:53 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('create')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 21:26:58 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('create')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 21:27:04 Europe/Berlin] Uncaught exception: 'Exception' with message 'No route matched.'
Stack trace: #0 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('create')
#1 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php' on line 130
[16-Jun-2022 22:52:13 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'session_regenerate_id(): Session ID cannot be regenerated when there is no active session'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'session_regener...', 'D:\\Dropbox\\#pro...', 23)
#1 D:\Dropbox\#programování\#projekt\ins_app\App\Auth.php(23): session_regenerate_id(true)
#2 D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php(73): App\Auth::login(Object(App\Models\User))
#3 [internal function]: App\Controllers\Home->loginAction()
#4 D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php(47): call_user_func_array(Array, Array)
#5 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('login', Array)
#6 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('home/login')
#7 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\App\Auth.php' on line 23
[16-Jun-2022 22:54:43 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'session_regenerate_id(): Session ID cannot be regenerated when there is no active session'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'session_regener...', 'D:\\Dropbox\\#pro...', 23)
#1 D:\Dropbox\#programování\#projekt\ins_app\App\Auth.php(23): session_regenerate_id(true)
#2 D:\Dropbox\#programování\#projekt\ins_app\App\Controllers\Home.php(73): App\Auth::login(Object(App\Models\User))
#3 [internal function]: App\Controllers\Home->loginAction()
#4 D:\Dropbox\#programování\#projekt\ins_app\Core\Controller.php(47): call_user_func_array(Array, Array)
#5 D:\Dropbox\#programování\#projekt\ins_app\Core\Router.php(121): Core\Controller->__call('login', Array)
#6 D:\Dropbox\#programování\#projekt\ins_app\public\index.php(35): Core\Router->dispatch('home/login')
#7 {main}
Thrown in 'D:\Dropbox\#programování\#projekt\ins_app\App\Auth.php' on line 23
